spring.application.name=demo
spring.datasource.url=jdbc:postgresql://ep-blue-shape-aiyd7ac9-pooler.c-4.us-east-1.aws.neon.tech:5432/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Z4BkFnm8VTvs
spring.datasource.driver-class-name=org.postgresql.Driver
